[build]
dockerfilePath = "deploy/console066-houston/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
sleepApplication = false
numReplicas = 1
