import test from 'node:test';import assert from 'node:assert/strict';
import {validateMetricImport,summarizeMetrics,privateMetrics} from '../lib/console-metrics.js';
import {marketingText} from '../lib/console-marketing.js';
const input={network:'googleAds',brandId:'6252950',from:'2026-10-01T00:00:00-03:00',to:'2026-10-07T17:02:49-03:00',rows:[[10,20,2,0,null,'20261001'],[15,null,3,1,9,'20261002']]};
test('imports preserve missing data, separate currency and correct coverage',()=>{const s=summarizeMetrics(validateMetricImport(input));assert.equal(s.metrics[1].value,20);assert.equal(s.metrics[1].availableDays,1);assert.equal(s.metrics[4].value,9);assert.equal(s.currency,null);assert.equal(s.source,'Metricool');});
test('rejects other brand, duplicate days, invalid dates, secrets and negative values',()=>{for(const bad of [{brandId:'6087160'},{rows:[input.rows[0],input.rows[0]]},{rows:[[1,2,3,4,5,'20261340']]},{rows:[[1,'',3,4,5,'20261001']]},{rows:[[1,-1,3,4,5,'20261001']]},{network:'unknown'}])assert.equal(validateMetricImport({...input,...bad}),null);});
test('follower series takes last observed number, rather than total',()=>{const s=summarizeMetrics(validateMetricImport({...input,network:'instagram',rows:[[10,null,null,null,1,null,'20261001'],[12,null,null,null,2,null,'20261002'],[null,null,null,null,null,null,'20261003']]}));assert.equal(s.metrics[0].value,12);assert.equal(s.metrics[1].value,null);assert.equal(s.metrics[4].value,3);});
test('payments unavailable does not fabricate zero sales or hide imports',async()=>{let calls=0;const sql=async()=>{if(++calls===1)return [{detail:validateMetricImport(input)}];throw new Error('db details must not escape');};const r=await privateMetrics(sql);assert.equal(r.sales.status,'No disponible');assert.equal(r.snapshots.length,1);assert.equal(r.sales.rows,undefined);});
test('marketing uses aggregates, excludes private fields and rejects unknown mission',()=>{const metrics={checkedAt:'now',sales:{status:'Conectado',rows:[]},snapshots:[summarizeMetrics(validateMetricImport(input))],directConnections:{ga4:'Pendiente'}};const text=marketingText('analitica',metrics,[{name:'BookFail',status:'En conversación',notes:'private phone',buyer_email:'private@example.com'}]);assert.match(text,/Metricool/);assert.match(text,/septiembre/);assert.doesNotMatch(text,/private phone|private@example/);assert.equal(marketingText('bad',metrics,[]),null);assert.ok(text.length<=4000);});
