import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,mkdtemp,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {stripTypeScriptTypes} from 'node:module';
const root=process.env.HOUSTON_SOURCE_DIR;
test('idle sweep preserves working/logging-in runtimes and races safely with a new request',{skip:!root},async()=>{
  const dir=await mkdtemp(join(tmpdir(),'houston-idle-test-')),file=join(dir,'process.ts');
  await writeFile(file,await readFile(join(root,'packages/host/src/launcher/process.ts'),'utf8'));
  execFileSync(process.execPath,['deploy/console066-houston/patch-runtime-limits.mjs',file]);
  const source=(await readFile(file,'utf8')).replace(/import[\s\S]*?from\s+"[^"]+";/g,'');
  const js=stripTypeScriptTypes(source,{mode:'transform'}).replace('export class ProcessLauncher','class ProcessLauncher');
  let state={busy:false,loginPending:false},probeHook=null;
  const module={exports:{}};
  const Class=Function('module','exports','setInterval','fetch','osAllocatePort','pollHealth',js+';return ProcessLauncher;')(module,module.exports,()=>({unref(){}}),async()=>{if(probeHook)probeHook();return {ok:true,json:async()=>state};},()=>1,()=>{});
  const launcher=new Class({spawner:{},workspaceDirFor:()=>'',dataDirFor:()=>'',mintToken:()=>''});
  const killed=[];launcher.sleep=async id=>{killed.push(id);launcher.running.delete(id);};
  const add=()=>{launcher.running.set('a',{handle:{port:1},token:'test'});launcher.lastTouch.set('a',Date.now()-20000);};
  add();state={busy:true,loginPending:false};await launcher.sweepIdle();assert.deepEqual(killed,[]);
  state={busy:false,loginPending:true};await launcher.sweepIdle();assert.deepEqual(killed,[]);
  state={};await launcher.sweepIdle();assert.deepEqual(killed,[]);
  state={busy:false,loginPending:false};probeHook=()=>launcher.lastTouch.set('a',Date.now());await launcher.sweepIdle();assert.deepEqual(killed,[]);
  probeHook=null;add();await launcher.sweepIdle();assert.deepEqual(killed,['a']);
  add();launcher.closed=true;await launcher.sweepIdle();assert.deepEqual(killed,['a']);
  launcher.closed=false;for(const id of ['one','two','three'])launcher.running.set(id,{handle:{port:1},token:'test'});
  await assert.rejects(launcher.ensureAwake({id:'four'}),/capacity/);
  assert.equal((await launcher.ensureAwake({id:'one'})).baseUrl,'http://127.0.0.1:1');
});
